name: gokafka

services:
  api:
    build: 
      context: .
      dockerfile: deployment/docker/api/Dockerfile
    image: ghcr.io/xoticdsign/api:${API_VERSION:-latest}
    ports: 
      - "8080:8080"
    depends_on: 
      messaging:
        condition: service_healthy
    extra_hosts:
      - "localhost:host-gateway"
  notificator:
    build: 
      context: .
      dockerfile: deployment/docker/notificator/Dockerfile
    image: ghcr.io/xoticdsign/notificator:${NOTIFICATOR_VERSION:-latest}
    depends_on: 
      messaging:
        condition: service_healthy
    extra_hosts:
      - "localhost:host-gateway"

  messaging:
    image: apache/kafka:latest
    ports: 
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      retries: 5
