name: API_CI

on:
  - push
  - pull_request

jobs:

  build:
    name: Building Binary
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build -o api cmd/api/main.go

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: api-binary
        path: api

  functional_tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download Binary
      uses: actions/download-artifact@v4
      with:
        name: api-binary

    - name: Run Tests
      run: go test -run _Functional -v ./...