name: CD 

on:
  
  push:
    tags:
      - v*

jobs:
  
  docker-deployment:
    name: Docker Deployment 
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Get Git Tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository}}

      - name: Build and Push Images
        run: |
          docker compose --project-directory . --file deployment/docker/docker-compose.yaml build
          docker tag ghcr.io/${{github.repository}} ghcr.io/${{github.repository}}:${{env.TAG}}
          docker push ghcr.io/${{github.repository}}:${{env.TAG}}

          
        
  
    