name: CI

on:
  - push
  - pull_request

jobs:

  build:
    name: Building Binary
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build API
      run: go build -o api cmd/api/main.go

    - name: Build Notificator
      run: go build -o notificator cmd/notificator/main.go

    - name: Upload API Binary
      uses: actions/upload-artifact@v4
      with:
        name: api-binary
        path: api
    
    - name: Upload Notificator Binary
      uses: actions/upload-artifact@v4
      with:
        name: notificator-binary
        path: notificator

  functional_tests:
    name: Functional Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Tests
      run: go test -run _Functional -v ./...