name: Notificator CD 

on:

  push:
    tags:
      - notificator-*

jobs:

  build:
    name: Building Binary
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build -o build/notificator cmd/notificator/main.go


 # functional-testing:
  #  name: Functional Tests
   # runs-on: ubuntu-latest
    #needs: build
#
 #   steps:
  #  - name: Checkout Repository
   #   uses: actions/checkout@v4
#
 #   - name: Run Tests
  #    run: go test -run _Functional -v ./internal/services/notificator/...

  docker-deployment:
    name: Docker Deployment 
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract Version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/notificator-* ]]; then
            echo "NOTIFICATOR_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
          
      - name: Build and Push Image
        run: docker compose --project-directory . --file deployment/docker/docker-compose.yaml build notificator --push 
        env:
          NOTIFICATOR_VERSION: ${{env.NOTIFICATOR_VERSION}}