name: Functional Tests

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -run _Functional -v ./...